In [3]:
import pandas as pd
import numpy as np

import env

In [4]:
def get_db_url(db):
    return f'mysql+pymysql://{env.user}:{env.password}@{env.host}/{db}'

In [6]:
query = '''
SELECT *
FROM customers
JOIN internet_service_types USING (internet_service_type_id)
'''

pd.read_sql(query, get_db_url('telco_churn'))

,internet_service_type_id,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,online_security,...,tech_support,streaming_tv,streaming_movies,contract_type_id,paperless_billing,payment_type_id,monthly_charges,total_charges,churn,internet_service_type
0,1,0002-ORFBO,Female,0,Yes,Yes,9,Yes,No,No,...,Yes,Yes,No,2,Yes,2,65.60,593.3,No,DSL
1,1,0003-MKNFE,Male,0,No,No,9,Yes,Yes,No,...,No,No,Yes,1,No,2,59.90,542.4,No,DSL
2,1,0013-MHZWF,Female,0,No,Yes,9,Yes,No,No,...,Yes,Yes,Yes,1,Yes,4,69.40,571.45,No,DSL
3,1,0015-UOCOJ,Female,1,No,No,7,Yes,No,Yes,...,No,No,No,1,Yes,1,48.20,340.35,No,DSL
4,1,0016-QLJIS,Female,0,Yes,Yes,65,Yes,Yes,Yes,...,Yes,Yes,Yes,3,Yes,2,90.45,5957.9,No,DSL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,3,9970-QBCDA,Female,0,No,No,6,Yes,No,No internet service,...,No internet service,No internet service,No internet service,1,No,4,19.70,129.55,No,None
7039,3,9972-EWRJS,Female,0,Yes,Yes,67,Yes,No,No internet service,...,No internet service,No internet service,No internet service,3,Yes,3,19.25,1372.9,No,None
7040,3,9975-GPKZU,Male,0,Yes,Yes,46,Yes,No,No internet service,...,No internet service,No internet service,No internet service,3,No,4,19.75,856.5,No,None
7041,3,9975-SKRNR,Male,0,No,No,1,Yes,No,No internet service,...,No internet service,No internet service,No internet service,1,No,2,18.90,18.9,No,None
7042,3,9986-BONCE,Female,0,No,No,4,Yes,No,No internet service,...,No internet service,No internet service,No internet service,1,No,3,20.95,85.5,Yes,None